const ADD_USER = 'ADD_USER';
const NEW_MESSAGE = 'NEW_MESSAGE';

const OFFLINE_USERS = 'OFFLINE_USERS';
const SEEN_MESSAGE = 'SEEN_MESSAGE';

const START_TYPING = 'START_TYPING';
const STOP_TYPING = 'STOP_TYPING';

const NOTIFICATION = 'NOTIFICATION';

export { ADD_USER, NEW_MESSAGE, OFFLINE_USERS, SEEN_MESSAGE, START_TYPING, STOP_TYPING, NOTIFICATION };
