const ADD_USER = 'ADD_USER';
const NEW_MESSAGE = 'NEW_MESSAGE';

const OFFLINE_USERS = 'OFFLINE_USERS';
const SEEN_MESSAGE = 'SEEN_MESSAGE';

export { ADD_USER, NEW_MESSAGE, OFFLINE_USERS, SEEN_MESSAGE };
